### ISSUE TITLE
Minor: Unable to check, whether token saved or not

### ISSUE THREAD

**Issue by okunev** [ccimpoi/ChromedFigma#1]
When the Save button is pressed, nothing happens.

<img width="415" alt="screen shot 2018-11-23 at 11 53 46" src="https://user-images.githubusercontent.com/3657051/48934815-8a18cc00-ef16-11e8-9f1d-1ca40a7e1d95.png">

**Comment by ccimpoi** [comment]
If there is no error at saving then it s saved.
If the setting is empty the app will prompt the issue when clicking the start button.
Pull requests are always welcome!
