### ISSUE TITLE
Back button (back interaction) is not exported

### ISSUE THREAD

**Issue by ondrejhomola** [ccimpoi/ChromedFigma#4]
Hi ccimpoi - thanks a lot for fixing the artboard export number. Is there anything that you can do with back buttons? I can assign back interaction (go to "previous page / where you came from") in Figma, but it gets lost when exporting.

Maybe something like this "href="#" onclick="history.go(-1)" could work :) Cheers!

**Comment by ccimpoi** [comment]
The problem is that the Figma API does not output any info related to interactions other than "navigate to another frame".
But I added a `__back__` hack so if you put that string in the name of the element and it will export a link with `history.back()`.
